### ISSUE TITLE
Generate type-safe Rust enums from PhysX enums

### ISSUE THREAD

**Issue by h3r2tic** [EmbarkStudios/physx-rs#10]
The code generator for `physx-sys` currently generates this peculiar construct for C++ enums:

```rust
pub mod PxMeshMidPhase{
    pub type Enum = u32;
    pub const eBVH33: Enum = 0u64 as u32;
    pub const eBVH34: Enum = 1u64 as u32;
    pub const eLAST: Enum = 2u64 as u32;
}
```

This is to match the C++ closely in terms of usage, and allow binary ops on flags.

While workable, the solution doesn't provide type safety, and makes it unwieldy to `match` on. We should investigate using more proper Rust enums an type-safe flags.

**Comment by Jake-Shadle** [comment]
Oops, this was fixed in #183
