### ISSUE TITLE
Add Mac CI build for aarch64 (Mac M1)

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/physx-rs#134]
We do test building for aarch64 for Android which gives some coverage, but would be good to have Mac aarch64 CI target as that is a primary platform for us, and PhysX codebase can fail specifically on it as showin in #133.

Not sure if the would nicely cross-compile from the existing Mac x86 agents, or if we should wait until GitHub has Mac aarch64 native agents (could take a long time).

**Comment by Jake-Shadle** [comment]
Oops, closed in #183

https://github.com/EmbarkStudios/physx-rs/blob/49176ebed029614e8e5072ce18c4440b99e82f08/.github/workflows/ci.yaml#L76-L94
