### ISSUE TITLE
Segfault (double free) on drop(PxShape)

### ISSUE THREAD

**Issue by rlidwka** [EmbarkStudios/physx-rs#180]
```rs
let mut material = physics.create_material(0.5, 0.5, 0.6, ()).unwrap();
let geometry = PxBoxGeometry::new(1., 1., 1.);
let flags = ShapeFlag::SceneQueryShape | ShapeFlag::SimulationShape | ShapeFlag::Visualization;
let mut shape = physics.create_shape(&geometry, &mut [&mut material], false, flags, ()).unwrap();
drop(material);
drop(shape);
```

This code releases `material` twice. Material itself is an owned pointer. And then shape releases all its materials (see line 100 below):

https://github.com/EmbarkStudios/physx-rs/blob/f0495378d0215179d73976ec3684ecb291f42ec8/physx/src/shape.rs#L96-L106

Either `create_shape` should consume material (i.e. `&mut [Owner<Material>]` instead of `&mut [&mut Material]`) or PxShape shouldn't release its materials on drop. I believe it's latter, but not completely sure.

**Comment by tgolsson** [comment]
Doing a bit of spring cleaning, is this still relevant? I'm a bit unsure about the issue; `release` is a ref-count manipulator.

**Comment by rlidwka** [comment]
Yes. If I insert this exact code into the example, it crashes.

Maybe I'm wrong about the source of the issue.

@tgolsson, are you able to reproduce this?
