### ISSUE TITLE
run error in msvs target

### ISSUE THREAD

**Issue by zyxia** [EmbarkStudios/physx-rs#199]
**Describe the bug**
in pxbind crate,run cargo run in msvc target,and result a error:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xtr1common:21:2: error: cannot mangle this template type parameter type yet
        static constexpr _Ty value = _Val;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: cannot mangle this template specialization type yet"

**To Reproduce**
1. run "cargo run" command in pxbind folder

**Expected behavior**
gen some *.rs file

**Screenshots**
<img width="1091" alt="image" src="https://github.com/EmbarkStudios/physx-rs/assets/5896264/8e40f380-47cc-4d0c-8e65-e9f1194e1ae4">

**Device:**
 - Windows 11

**Additional context**
i test llvm 16 and 15,all failed in this convext,and change version of vc ()vs2019 ,vs2017,vs2022  ),and   failed too

**Comment by tgolsson** [comment]
@Jake-Shadle any initial thoughts?

**Comment by Jake-Shadle** [comment]
`pxbind` has never been run on Windows, it's not expected to work.

**Comment by Jake-Shadle** [comment]
This is a clang error, there's really nothing we can do.
