### ISSUE TITLE
Spring/damper has no effect in driving articulation joint

### ISSUE THREAD

**Issue by mlp1802** [EmbarkStudios/physx-rs#202]
It seems that no matter what value I use for spring or damper, it has no effect on the simulation. I can set these values to whatever, zero or a billion, it has no effect. I'm trying to drive a joint towards an orientation. The ragdoll is very unstable since there is zero damping, the only parameter that seems to have an effect is max_force. I'm thinking there might be something wrong with the binding for this function "PxArticulationJointReducedCoordinate_setDriveParams_mut(joint, axis, &drive)" or something like that? unless I completely misunderstood something.
```rust
pub fn set_articulation_joint_reduced_target(
    joint: PtrArticulationJointReducedCoordinate,
    axis: PxArticulationAxis,
    max_force: f32,
    spring: f32,
    damper: f32,
    target: f32,
) {
    unsafe {
        println!("Spring/damper {} {}", spring, damper);
        let drive = PS::PxArticulationDrive_new_1(
            spring,
            damper,
            max_force,
            PS::PxArticulationDriveType::Target,
        );

        PS::PxArticulationJointReducedCoordinate_setDriveParams_mut(joint, axis, &drive);
        PS::PxArticulationJointReducedCoordinate_setDriveTarget_mut(joint, axis, target, true);
        PS::PxArticulationJointReducedCoordinate_setFrictionCoefficient_mut(joint, 2.0);
    }
}
```

**Comment by tgolsson** [comment]
How is the joint configured?

**Comment by mlp1802** [comment]
> How is the joint configured? 

All Spherical joints, with limits but rather large limits.

**Comment by tgolsson** [comment]
Are you setting motion type per axis?

**Comment by tgolsson** [comment]
Hmm. I'd narrow it down a bit by using a limited spherical joint, and probably using a Force drive type rather than Target. That'd be a more regular setup I think. This seems like a configuration issue, more so than a binding problem until we can prove the opposite. Articulation joints and drives are a lot less forgiving for configuration errors than their regular variants.

Just to double-check though; @blunzn or @bpaberg -- you've both looked at the articulations recently; did you notice any issues with drives?

**Comment by mlp1802** [comment]
I could try to use velocity drive to see if it makes a difference, it should be possible to drive towards an orientation using velocity as well, by setting velocity to zero when target is reached.

**Comment by mlp1802** [comment]
I'm not sure why force drive would work better?

**Comment by mlp1802** [comment]
Ok once I'm home I'll make a minimal example to try to reproduce it.

**Comment by mlp1802** [comment]
My bad, I should've use FORCE joint drive type instead of TARGET.

**Comment by tgolsson** [comment]
Thanks for the follow-up @mlp1802!
