### ISSUE TITLE
Please add PxCreateCudaContextManager method to enable Gpu acceleration

### ISSUE THREAD

**Issue by kgb7711** [EmbarkStudios/physx-rs#220]
I found that the library does not support GPU acceleration, please add PxCreateCudaContextManager method to enable GPU acceleration. Thanks!

**Comment by repi** [comment]
this library does not include or compile the GPU path of PhysX as it is a significant additional set of libraries and code, so it out of scope of the current supported features.

if someone would be interested in taking the time to fully integrate and build out the GPU path of PhysX and do a PR we could consider including it if it is a toggle feature and not too complex. 

but will close this for now as there is no GPU support in the crate
