### ISSUE TITLE
Compile errors when building from source

### ISSUE THREAD

**Issue by mmusu3** [EmbarkStudios/physx-rs#43]
**Describe the bug**
Compilation fails when attempting to build the project on Windows 10, following the "How to build" instructions in the readme. In the console I get the following messages:
```
error: could not find native static library `PhysXVehicle_static_64`,` perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `physx-sys`.
warning: build failed, waiting for other jobs to finish...
error: attempt to shift right with overflow
   --> physx\src\articulation_reduced_coordinate.rs:494:23
    |
494 |         let (a, b) = ((self.ptr as usize >> 32) as u32, self.ptr as usize as u32);
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(exceeding_bitshifts)]` on by default

error: aborting due to previous error

error: could not compile `physx`.
```

**To Reproduce**
Run `cargo build --release` from the cloned physx-rs directory

**Additional context**
I don't have any rust experience, and only a small amount of C/C++ experience. I would like to use the physx-sys C API to build a standalone DLL that I can use from C#.

**Comment by repi** [comment]
Interesting, haven't seen that compile error neither locally nor on the CI here.

Which version of Rust are you using? `cargo --version`

**Comment by mmusu3** [comment]
cargo 1.41.0 (626f0f40e 2019-12-03)

**Comment by repi** [comment]
That is indeed the latest stable version, and same that we are using.

Looks like you have two different problems also, one is the bitshifting warning/error, and the other one looks like a `physx-sys` compile and link error.

@h3r2tic @tgolsson any ideas?

**Comment by tgolsson** [comment]
@mmusu3 Shot in the dark, but are you on a 32-bit system, or compiling with that as a target? The error message suggests that `usize` is 32-bits long, and it's complaining about what I'm guessing is a missing 64-bit library.

**Comment by mmusu3** [comment]
I'm on Windows 10 64bit. I don't know about specifying a target, I only entered the basic compile commands.

**Comment by mmusu3** [comment]
Well I reinstalled rust and now the pointer error is gone. When installing rust the first time I must have changed the default options. When reviewing it seemed to be a 64bit option. Now when compiling the errors are:
```
error: could not find native static library `PhysXVehicle_static_64`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `physx-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by tgolsson** [comment]
That's good, one less mystery to solve .So for the remaining issue, it seems very similar to the error reported (and fixed by @h3r2tic) [here](https://github.com/EmbarkStudios/physx-rs/issues/35). 

I'm unfortunately on Linux so I can't check it locally, but can you see if the library gets built at all? We've got some heuristics [here](https://github.com/EmbarkStudios/physx-rs/blob/master/physx-sys/build.rs#L49) to find the output path, I'm wondering whether that gives us the wrong output directory.

**Comment by mmusu3** [comment]
I'm having no luck recently. I cleared out the target directory and rebuilding now returns the original errors again. I'm not sure where the library is supposed to be output, I'm a bit lost in these folders.

**Comment by mmusu3** [comment]
One question. Does physx-rs require first building the PhysX projects inside inside or is that handled by the physx-rs build scripts?

**Comment by tgolsson** [comment]
The physx-rs build script should build everything required. For me (on Linux, though), both `cargo build --release` and `cargo run --example ball` work immediately after a git clone. I'm assuming the latter also fails for you?

**Comment by mmusu3** [comment]
`cargo run --example ball` fails with a reduced set of errors. Output:
```
   Compiling physx-sys v0.2.4+4.1.1 (D:\Users\Michael\Projects\physx-rs\physx-sys)
error: could not find native static library `PhysXVehicle_static_64`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `physx-sys`.
```

**Comment by tgolsson** [comment]
As expected then. I've got nothing more at the moment, so I'll go ahead and hand over to @h3r2tic as he fixed the previous similar issue.

If you can try to locate the output libraries that'd likely be helpful though. For me, they are located under `target/release/build/physx-sys-4b83134f41375d91/out/bin/linux.clang/profile/` starting from the root of the repository. Yours should be under a similar path, probably with a different ID (the `4b83134f41375d91` part) and likely a `win.x86_64.vc...` part instead of `linux.clang`.

**Comment by mmusu3** [comment]
I have `target\release\build\physx-sys-1d9a38202e6d47ee\out\bin\win.x86_32.vc142.md\profile\` I'm guessing the x86_32 part is the issue. I trying to understand this build script to see how it makes that decision. Inside `physx-sys/PhysX/physx/bin` there is a `win.x86_64.vc142.mt` folder that I would expect it to use but isn't?

**Comment by tgolsson** [comment]
Yeah, that does indeed seem to be the issue. Are you installing Rust via `rustup`? Can you show the output from `rustup show`? And maybe also try building with `cargo build --release --target x86_64-pc-windows-msvc` to force 64-bit target?

**Comment by mmusu3** [comment]
```
Default host: i686-pc-windows-msvc
rustup home:  C:\Users\Michael\.rustup

installed toolchains
--------------------

stable-i686-pc-windows-msvc
nightly-i686-pc-windows-msvc

active toolchain
----------------

stable-i686-pc-windows-msvc (default)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

**Comment by tgolsson** [comment]
Aye, that is indeed 32-bit toolchains.

**Comment by mmusu3** [comment]
rustup-init.exe seems to indicate that it will install x86-64 yet `rustup toolchain list` tells me only i686 is installed ☹️

**Comment by tgolsson** [comment]
That is weird. Does it give you any information if you attempt to force it to install 64-bit with `rustup toolchain install stable-x86_64-pc-windows-msvc`?

**Comment by mmusu3** [comment]
The x64 toochain seems to be installed now. Not sure why the installer exe is so misleading. Here is the end part of the opening test when using rustup-init.exe:
```
Current installation options:


   default host triple: x86_64-pc-windows-msvc
     default toolchain: stable
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
```

**Comment by repi** [comment]
Sweet that you got it working! We should add an explicit error message for unsupported build targets like 32-bit Windows, that would have saved some debugging

**Comment by mmusu3** [comment]
Now that I am able to generate the wrapper files I can continue work towards creating a C API wrapper dll however due to my lack of experience with C++ it is proving to be out of my depth. I am going to leave this for now and return to it later. I might file a new issue requesting an easier way to generate such a wrapper as it would be of great use to allow PhysX to be used not just from C# but also many other languages that can interface with C. Since the original issues reported here have been resolved I will close this.
