### ISSUE TITLE
Add #[derive(Debug)] to structs.

### ISSUE THREAD

**Issue by NiklasNummelin** [EmbarkStudios/physx-rs#51]
**Is your feature request related to a problem? Please describe.**
Sometimes it is nice to be able to inspect structs without having to print every field.

**Describe the solution you'd like**
Adding #[derive(Debug)] to all structs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A.

**Comment by Jake-Shadle** [comment]
Fixed in #183, enabling the `debug-structs` feature flag enables `Debug` on all generated POD structs/unions.
