### ISSUE TITLE
Add trampolines for PxSweepCallback, PxRaycastCallback and PxOverlapCallback

### ISSUE THREAD

**Issue by Hentropy** [EmbarkStudios/physx-rs#99]
#### The Problem
Currently, scene queries are not usable because the callback types they need are not instantiable.

#### The Solution
Add trampolines for PxSweepCallback, PxRaycastCallback and PxOverlapCallback.

#### Alternatives
I tried passing in the callback viz MaybeUninit, but it crashes with a memory access violation.  It's theoretically possible to cobble the vtable together in Rust, but a trampoline is the best solution.

#### Context
I have written [call throughs](https://github.com/Hentropy/physx-rs/blob/main/physx/src/scene.rs#L502) for `sweep`, `overlap`, and `raycast` but without these types they cannot be called.

**Comment by NickCaplinger** [comment]
Hey @Hentropy, I've got a rough implementation working for this right now that supports usage of PxRaycastBuffer and user-defined PxRaycastCallback implementations. I should have a PR ready this weekend for raycasts, sweeps, and overlaps and I'd love to have you review it when you have the chance. :)

**Comment by Hentropy** [comment]
@NickCaplinger You're a legend, thank you.  Gimme a ping and I'll take a look 😄

**Comment by Jake-Shadle** [comment]
Closed in #181
